blank_issues_enabled: false
contact_links:
  - name: ğŸ…±ï¸ Origincraft æœ€æ–°å®£ä¼ è§†é¢‘
    url: https://www.bilibili.com/video/BV1Qm4y1L7pK/?spm_id_from=333.999.0.0
    about: è¾ƒä¸ºè¯¦ç»†çš„ä»‹ç»ä»¥åŠä¸‹è½½é€”å¾„/å®˜ç½‘åœ°å€/QQç¾¤/ç®€ä»‹ç­‰

  - name: ğŸ”— Origincraft å®˜ç½‘
    url: https://www.huaijiujing.cn/
    about: è¿™é‡ŒåŒ…å«äº†æœ€æ–°çš„æ¶ˆæ¯/FAQ/ç‰ˆæœ¬å…¬æµ‹ä»¥åŠæ•´åˆåŒ…èµ„æºçš„ä¸‹è½½ï¼ˆåŠ¡å¿…ï¼æ¥çœ‹ï¼ï¼‰

  - name: ğŸ§‘â€ğŸ”¬å›¢é˜Ÿæ‹›äººï¼ˆç•Œé¢æœªåˆ¶ä½œï¼Œè”ç³»è¯·å‰å¾€é‚®ç®±W211010999@163.comæˆ–QQ3208301509è”ç³»ï¼‰
    url: https://404
    about: å¦‚æœæœ‰æ•´åˆåŒ…åˆ¶ä½œ/é­”æ”¹ç»éªŒçš„ï¼Œæˆ–æœ‰èµ·è‰æ–‡æ¡ˆ/å‰§æƒ…åŸºç¡€çš„è¯·ç«‹å³ï¼ç«‹å³è·³è½¬â†’
